save_interval: 1000
save_interval_unsharded: 100000
save_num_checkpoints_to_keep: 1
save_num_unsharded_checkpoints_to_keep: 1
sweep:
- device_eval_batch_size: 64
  device_train_microbatch_size: 64
  eval_interval: 37244
  max_duration: 372443
  model:
    context_length: 512
    d_model: 512
    n_heads: 8
    n_layers: 6
  params: 150221312
  ratio: 162.48309992126815
  scheduler:
    t_warmup: 74488
  tokens: 24408424448
  total_flops: 22000000000000000000
training:
  batch_size: 128
wandb:
  group: smooth
  project: smooth
